security:
    encoders:
        PlanBundle\Entity\User:
            algorithm: bcrypt

    providers:
         db_provider:
            entity:
                class: PlanBundle:User
                property: username

    firewalls:
        main:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: /logout

    access_control:
        - { path: ^/(poniedzialek|wtorek|sroda|czwartek|piatek), roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
