<?php

namespace PlanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends EntityRepository
{
    public function findAllByDay($userId, $day)
    {
        $query = $this->getEntityManager()
        ->createQuery(
            'SELECT p.id, p.task, p.startTime, p.endTime FROM PlanBundle:Plan p
            WHERE p.user = :id_user AND p.day = :day
            ORDER BY p.startTime ASC')
        ->setParameters([
            'id_user' => $userId,
            'day' => $day
        ]);

        return $query->getResult();
    }
}
